version: '3'
services:
        db:
            image: mdillon/postgis:9.6-alpine
            environment:
                - POSTGRES_PASSWORD=senhaMapas
                - POSTGRES_USER=mapas
                - POSTGRES_DB=mapas

        deploy:
                build: .
                links:
                    - db:db
                depends_on:
                    - db
                working_dir: /var/www/html/scripts
                volumes:
                    - .:/var/www/html
                environment:
                    - PGPASSWORD=senhaMapas
                command: ["./deploy.sh", "localhost"]

        nginx:
            image: nginx:mainline-alpine
            volumes:
                - .:/var/www/html
                - ./documentation/site.conf:/etc/nginx/conf.d/default.conf
            depends_on:
                - deploy
                - php
            links:
                    - php:php
            ports:
                - "80:80"

        php:
            build:
              context: .
              dockerfile: Dockerfile-php
            volumes:
                - .:/var/www/html
                - ./documentation/php-conf.d/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
                - ./documentation/php-conf.d/clear-env.conf:/usr/local/etc/php-fpm.d/zz-clear-env.conf
            links:
                - db:db
            depends_on:
                - db
                - deploy
            environment:
                - TZ=America/Sao_Paulo
