version: '3'
services:
        db:
            image: mdillon/postgis:9.6-alpine
            environment:
                - POSTGRES_PASSWORD=senhaMapas
                - POSTGRES_USER=mapas
                - POSTGRES_DB=mapas

        deploy:
                build: .
                links:
                    - db:db
                depends_on:
                    - db
                working_dir: /var/www/html/scripts
                volumes:
                    - .:/var/www/html
                environment:
                    - PGPASSWORD=senhaMapas
                command: ["./deploy.sh", "dev.mapas.cultura.gov.br"]

        nginx:
            image: nginx:mainline-alpine
            volumes:
                - .:/var/www/
            depends_on:
                - db
                - deploy
                - php
            links:
                - php
            ports:
                - "80:80"

        php:
            image: php:5-fpm-alpine
            volumes:
                - .:/var/www/html
            links:
                - db:db
            depends_on:
                - db
                - deploy
